cargo-features = ["strip"]

[package]
name = "mmtc"
version = "0.1.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"
license = "MPL-2.0"
description = "Minimal mpd terminal client"
homepage = "https://github.com/figsoda/mmtc"
repository = "https://github.com/figsoda/mmtc"
readme = "README.md"
keywords = ["mpd", "music", "tui"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.34"
crossterm = "0.18.2"
dirs = "3.0.1"
expand = "0.1.3"
ron = "0.6.2"
serde = { version = "1.0.117", features = ["derive"] }
structopt = "0.3.20"

[dependencies.tokio]
version = "0.3.3"
features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"]

[dependencies.tui]
version = "0.12.0"
default-features = false
features = ["crossterm", "serde"]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
