cargo-features = ["strip"]

[package]
name = "mmtc"
version = "0.2.2"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"
description = "Minimal mpd terminal client that aims to be simple yet highly configurable"
readme = "README.md"
homepage = "https://github.com/figsoda/mmtc"
repository = "https://github.com/figsoda/mmtc"
license = "MPL-2.0"
keywords = ["cli", "mpd", "music", "terminal", "tui"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.34"
crossterm = "0.18.2"
dirs-next = "2.0.0"
expand = "0.2.0"
ron = "0.6.2"
serde = { version = "1.0.117", features = ["derive"] }
structopt = "0.3.20"

[dependencies.tokio]
version = "0.3.3"
features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"]

[dependencies.tui]
version = "0.12.0"
default-features = false
features = ["crossterm", "serde"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = "symbols"
