[package]
name = "mmtc"
version = "0.2.13"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"
description = "Minimal mpd terminal client that aims to be simple yet highly configurable"
readme = "README.md"
homepage = "https://github.com/figsoda/mmtc"
repository = "https://github.com/figsoda/mmtc"
license = "MPL-2.0"
keywords = ["cli", "mpd", "music", "terminal", "tui"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.42"
async-io = "1.6.0"
async-net = "1.6.1"
clap = "3.0.0-beta.2"
crossbeam-queue = "0.3.2"
crossterm = "0.20.0"
dirs-next = "2.0.0"
expand = "0.2.0"
futures-lite = "1.12.0"
ron = "0.6.4"
serde = { version = "1.0.127", features = ["derive"] }

[dependencies.tui]
version = "0.16.0"
default-features = false
features = ["crossterm", "serde"]

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
